// Generated by tools/gen_fonts.py from Inter (SIL OFL 1.1) - do not edit.
#pragma once
#include <stdint.h>

typedef struct { uint16_t cp; uint16_t off; uint8_t w, h; int8_t xoff, yoff; uint16_t adv16; } pod_glyph_t;
typedef struct { const pod_glyph_t *glyphs; const uint8_t *bitmap; uint16_t count; uint8_t ascent, line_h; } pod_font_t;

extern const pod_font_t pod_font_title;   // Inter Bold 19px
extern const pod_font_t pod_font_body;   // Inter Medium 13px
extern const pod_font_t pod_font_status;   // Inter SemiBold 11px
extern const pod_font_t pod_font_small;   // Inter Medium 10px
