#!/usr/bin/env python3
"""Generate the "SH" monogram (common/pod_logo.c) from Inter Bold.

    python3 tools/gen_logo.py      (needs Pillow)

Output: an anti-aliased 8-bit alpha mask, drawn in white (or any colour) by pod_display.
"""
import os
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
SIZE, SS = 40, 8                       # final size, supersampling factor
TEXT, TRACKING = "SH", 0.06            # letter spacing as a fraction of the font size

big = SIZE * SS
img = Image.new("L", (big, big), 0)
d = ImageDraw.Draw(img)
ring = 1.6 * SS
d.ellipse((ring / 2, ring / 2, big - ring / 2 - 1, big - ring / 2 - 1), outline=255, width=int(ring))

font = ImageFont.truetype(os.path.join(HERE, "..", "third_party", "inter", "Inter-Bold.ttf"), int(15.5 * SS))
widths = [d.textlength(c, font=font) for c in TEXT]
track = TRACKING * font.size
total = sum(widths) + track * (len(TEXT) - 1)
x = (big - total) / 2
asc, desc = font.getmetrics()
bbox = font.getbbox("SH")               # visual height of the capitals
y = (big - (bbox[3] - bbox[1])) / 2 - bbox[1]
for c, w in zip(TEXT, widths):
    d.text((x, y), c, font=font, fill=255)
    x += w + track

img = img.resize((SIZE, SIZE), Image.LANCZOS)
px = [v if v >= 10 else 0 for v in img.tobytes()]   # drop resampling ringing
lines = ["// Generated by tools/gen_logo.py from Inter Bold (SIL OFL 1.1) - do not edit.",
         '#include "pod_logo.h"', "",
         f"const uint8_t pod_logo_alpha[POD_LOGO_SIZE * POD_LOGO_SIZE] = {{"]
for r in range(SIZE):
    lines.append("    " + ",".join(f"{v:3d}" for v in px[r * SIZE:(r + 1) * SIZE]) + ",")
lines.append("};")
open(os.path.join(HERE, "..", "common", "pod_logo.c"), "w").write("\n".join(lines) + "\n")
open(os.path.join(HERE, "..", "common", "pod_logo.h"), "w").write(
    "// \"SH\" monogram, generated by tools/gen_logo.py\n#pragma once\n#include <stdint.h>\n\n"
    f"#define POD_LOGO_SIZE {SIZE}\nextern const uint8_t pod_logo_alpha[POD_LOGO_SIZE * POD_LOGO_SIZE];\n")
img.resize((SIZE * 6, SIZE * 6), Image.NEAREST).save("/tmp/claude-0/logo_preview.png")
print("wrote common/pod_logo.c")
