#!/usr/bin/env python3
"""Pre-render Inter glyphs to 4-bit anti-aliased bitmaps as C arrays.
Run from the repo root:  python3 tools/gen_fonts.py   (needs Pillow)
Output: common/pod_fonts.c / common/pod_fonts.h
"""
from PIL import Image, ImageDraw, ImageFont
import os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TTF = os.path.join(ROOT, 'third_party', 'inter')

FONTS = [  # (c name, file, pixel size)
    ('pod_font_title',  'Inter-Bold.ttf',     19),
    ('pod_font_body',   'Inter-Medium.ttf',   13),
    ('pod_font_status', 'Inter-SemiBold.ttf', 11),
    ('pod_font_small',  'Inter-Medium.ttf',   10),
]
CODEPOINTS = list(range(0x20, 0x7F)) + list(range(0xA0, 0x100)) + \
             [0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2022, 0x2026]

def render(name, file, size):
    f = ImageFont.truetype(os.path.join(TTF, file), size)
    ascent, descent = f.getmetrics()
    glyphs, bitmap = [], bytearray()
    for cp in CODEPOINTS:
        ch = chr(cp)
        adv16 = round(f.getlength(ch) * 16)
        bbox = f.getbbox(ch, anchor='ls')          # relative to baseline origin
        if bbox[2] <= bbox[0] or bbox[3] <= bbox[1]:
            glyphs.append((cp, len(bitmap), 0, 0, 0, 0, adv16)); continue
        x0, y0, x1, y1 = bbox
        w, h = x1 - x0, y1 - y0
        im = Image.new('L', (w, h), 0)
        ImageDraw.Draw(im).text((-x0, -y0), ch, font=f, fill=255, anchor='ls')
        off = len(bitmap)
        px = im.load()
        for y in range(h):
            row = [min(15, (px[x, y] + 8) // 17) for x in range(w)]
            if w % 2: row.append(0)
            for i in range(0, len(row), 2):
                bitmap.append((row[i] << 4) | row[i + 1])
        # yoff = distance from top of line box (ascent above baseline) to bitmap top
        glyphs.append((cp, off, w, h, x0, ascent + y0, adv16))
    return ascent, descent, glyphs, bitmap

h_out = ['// Generated by tools/gen_fonts.py from Inter (SIL OFL 1.1) - do not edit.',
         '#pragma once', '#include <stdint.h>', '',
         'typedef struct { uint16_t cp; uint16_t off; uint8_t w, h; int8_t xoff, yoff; uint16_t adv16; } pod_glyph_t;',
         'typedef struct { const pod_glyph_t *glyphs; const uint8_t *bitmap; uint16_t count; uint8_t ascent, line_h; } pod_font_t;',
         '']
c_out = ['// Generated by tools/gen_fonts.py from Inter (SIL OFL 1.1) - do not edit.',
         '#include "pod_fonts.h"', '']
total = 0
for name, file, size in FONTS:
    asc, desc, glyphs, bm = render(name, file, size)
    total += len(bm) + len(glyphs) * 10
    c_out.append(f'static const uint8_t {name}_bm[{len(bm)}] = {{')
    for i in range(0, len(bm), 24):
        c_out.append('    ' + ','.join(f'0x{b:02x}' for b in bm[i:i + 24]) + ',')
    c_out.append('};')
    c_out.append(f'static const pod_glyph_t {name}_g[{len(glyphs)}] = {{')
    for g in glyphs:
        c_out.append('    {0x%04x,%d,%d,%d,%d,%d,%d},' % g)
    c_out.append('};')
    c_out.append(f'const pod_font_t {name} = {{ {name}_g, {name}_bm, {len(glyphs)}, {asc}, {asc + desc} }};')
    c_out.append('')
    h_out.append(f'extern const pod_font_t {name};   // Inter {file[6:-4]} {size}px')
open(os.path.join(ROOT, 'common', 'pod_fonts.h'), 'w').write('\n'.join(h_out) + '\n')
open(os.path.join(ROOT, 'common', 'pod_fonts.c'), 'w').write('\n'.join(c_out) + '\n')
print(f'fonts: {total/1024:.1f} KB flash')
